import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Finanzas con Python</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Finanzas con <a href="https://python.org">Python</a>
        </h1>
        
        <p className={styles.description}>
          Curso de Python con aplicaciones financieras
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Curso &rarr;</h2>
            <p>Desde lo básico en Python hasta Objetos y más ...</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Aplicaciones &rarr;</h2>
            <p>Financieras, actuariales, Web Scraping, bots, ...</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Prácticas &rarr;</h2>
            <p>Aprender a programar resolviendo ejercicios ...</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Retos &rarr;</h2>
            <p>
              Nuevos proyectos ... ... ¡Sigue creciendo!
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <small><a href="https://github.com/financieras/pythonisa">Made with ❤ by A. Aparicio • View on Github</a></small>
      </footer>
    </div>
  )
}
