import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Finanzas con Python</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Finanzas con <a href="https://python.org">Python</a>
        </h1>
        
        <p className={styles.description}>
          Curso de Python con aplicaciones financieras
        </p>

        <div className={styles.grid}>
          <a href="http://nbviewer.org/github/financieras/pyCourse/tree/main/jupyter" className={styles.card}>
            <h2>Curso &rarr;</h2>
            <p>Desde lo básico en Python hasta Objetos y más ...</p>
          </a>

          <a href="http://nbviewer.org/github/financieras/pyCourse/tree/main/ejemplos" className={styles.card}>
            <h2>Ejemplos &rarr;</h2>
            <p>Casos resueltos por varios métodos ...</p>
          </a>

          <a
            href="http://nbviewer.org/github/financieras/pyCourse/tree/main/practicas"
            className={styles.card}
          >
            <h2>Prácticas &rarr;</h2>
            <p>Aprender a programar resolviendo ejercicios ...</p>
          </a>

          <a
            href="https://altocodigo.blogspot.com/p/aprender-haciendo.html"
            className={styles.card}
          >
            <h2>Retos &rarr;</h2>
            <p>
              Nuevos proyectos ... ... ¡Sigue creciendo!
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <small><a href="https://github.com/financieras/pythonisa">Made with ❤ by A. Aparicio • View on Github</a></small>
      </footer>
    </div>
  )
}
